---
title: "sentiment_plots"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

### Should I manipulate the length of the graphs to reflect the length of the novels?

## 'The Road'

```{r}
theroad_sentiments %>%
  ggplot(aes(x = line, y = bing)) +
  geom_bar(stat = "identity") +
  annotate("label", x = 238.5, y = 5, label = "They discover the bunker filled with supplies", hjust = 0.5, label.size = 0, size = 3, color = "#2b2b2b") +
  annotate("segment", x = 238.5, xend = 238.5, y = 4.6, yend = 3.2, arrow = arrow(length = unit(0.02, "npc")), color = "#2b2b2b") +
  annotate("label", x = 173, y = 3, label = "They find the cellar\nof imprisoned people", hjust = 0.5, label.size = 0, size = 3, color = "#2b2b2b") +
  annotate("segment", x = 177.5, xend = 177.5, y = 2, yend = 0.5, arrow = arrow(length = unit(0.02, "npc")), color = "#2b2b2b") +
  theme_minimal() +
  labs(
    title = expression(paste("Sentiment in ", italic("The Road"), " by Cormac McCarthy")),
    y = "Sentiment",
    caption = "Bleak Novel LMAO"
  ) +
  theme(
    plot.title = element_text(size = 14, face = "bold", color = "#2b2b2b"),
    plot.caption = element_text(color = "#2b2b2b"),
    axis.title.y = element_text(color = "#2b2b2b"),
    axis.text.y = element_text(color = "#2b2b2b"), 
    axis.text.x = element_blank(),
    axis.title.x = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    panel.grid.major.y = element_blank(),
    panel.grid.minor.y = element_blank()
  )
```

## 'All the Pretty Horses'

```{r}
prettyhorses_sentiments %>%
  ggplot(aes(x = line, y = bing)) +
  geom_bar(stat = "identity", aes(fill = bing >= 0), width = 1) + 
  scale_fill_manual(values = c("FALSE" = "#36939b", "TRUE" = "goldenrod4")) +
  theme_minimal() +
  labs(
    title = expression(paste("Sentiment in ", italic("All The Pretty Horses"), " by Cormac McCarthy")),
    y = "Sentiment",
    caption = "More of a wild ride. Eh, see what I did there"
  ) +
  theme(
    plot.title = element_text(size = 14, face = "bold", color = "tan4"),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    panel.grid.major.y = element_blank(),
    panel.grid.minor.y = element_blank(),
    axis.title.x = element_blank(),
    axis.text.x = element_blank(),
    axis.title.y = element_text(color = "tan4"),
    axis.text.y = element_text(color = "tan4"),
    plot.caption = element_text(color = "tan4"),
    legend.position = "none"
  )
```

## 
